global:
  registry: docker.io/cilium
  tag: v1.7.6
  containerRuntime:
    integration: crio
agent:
  cniInstallScript: /cni-install.sh
  cniUninstallScript: /cni-uninstall.sh
  initScript: /init-container.sh
  initImage: cilium
operator:
  image: operator